name: build-jvm-backend
description: Builds a JVM backend application and publishes a Docker image
inputs:
  javaVersion:
    description: 'The version of Java to use'
    default: '21'
    required: true
  githubToken:
    description: 'The GitHub token to use for authentication'
    required: true
  imageRegistry:
    description: 'The name of the image registry to push the Docker image to'
    required: true
  imageRegistryUser:
    description: 'The owner of the image registry'
    required: true
  imageRegistryPassword:
    description: 'The password or token for the image registry'
    required: true
  imageName:
    description: 'The name of the Docker image to build and push'
    required: true

runs:
    using: 'composite'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.javaVersion }}

      - name: Semantic Release Version
        id: semantic_release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ inputs.githubToken }}
          RELEASE_CONFIG: |
            {
              "branches": [
                "main"
              ],
              "plugins": [
                [
                  "@semantic-release/commit-analyzer",
                  {
                    "preset": "conventionalcommits",
                    "releaseRules": [
                      { "type": "feat!", "release": "major" },
                      { "type": "feat", "release": "minor" },
                      { "type": "fix", "release": "patch" },
                      { "type": "chore", "release": "patch" }
                    ]
                  }
                ],
                "@semantic-release/release-notes-generator",
                "@semantic-release/changelog",
                "@semantic-release/github"
              ]
            }

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle
        shell: bash
        run: ./gradlew build
        env:
          GH_ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ inputs.githubToken }}

      - name: Check New Release Version
        shell: bash
        run: echo "New release version is ${{ steps.semantic_release.outputs.new_release_version }}"

      - name: Login to ghrc.io
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.imageRegistry }}
          username: ${{ inputs.imageRegistryUser }}
          password: ${{ inputs.imageRegistryPassword }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ inputs.imageRegistry }}/${{ inputs.imageRegistryUser }}/${{ inputs.imageName }}:latest,
            ${{ inputs.imageRegistry }}/${{ inputs.imageRegistryUser }}/${{ inputs.imageName }}:${{ steps.semantic_release.outputs.new_release_version }}